// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UsersBusinessCategory string

const (
	UsersBusinessCategorySTUDENT UsersBusinessCategory = "STUDENT"
	UsersBusinessCategoryTEACHER UsersBusinessCategory = "TEACHER"
)

func (e *UsersBusinessCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersBusinessCategory(s)
	case string:
		*e = UsersBusinessCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersBusinessCategory: %T", src)
	}
	return nil
}

type NullUsersBusinessCategory struct {
	UsersBusinessCategory UsersBusinessCategory
	Valid                 bool // Valid is true if UsersBusinessCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersBusinessCategory) Scan(value interface{}) error {
	if value == nil {
		ns.UsersBusinessCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersBusinessCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersBusinessCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersBusinessCategory), nil
}

type Event struct {
	EventID       uint32
	Name          string
	Description   string
	EventDate     time.Time
	CreationDate  sql.NullTime
	ParentEventID sql.NullInt32
}

type Photo struct {
	PhotoID      uint32
	PathToPhoto  string
	CreationDate sql.NullTime
	EventID      uint32
}

type RecognizedUser struct {
	RecognizedUserID uint32
	UserID           uint32
	PhotoID          uint32
}

type Session struct {
	SessionID    uint32
	UserID       uint32
	CreationDate time.Time
	SessionToken string
}

type User struct {
	UserID           uint32
	SignupDate       time.Time
	LastSigninDate   time.Time
	SigninLocked     bool
	SigninLockedDate sql.NullTime
	IsAdmin          bool
	Email            string
	FullName         string
	BusinessCategory UsersBusinessCategory
	DepartmentNumber string
}

type UserFolder struct {
	UserFolderID   uint32
	IsSubFolder    sql.NullBool
	Name           string
	Description    string
	CreationDate   sql.NullTime
	UserID         uint32
	ParentFolderID sql.NullInt32
}
